import type { Category } from "@/lib/types"

export const categories: Category[] = [
  {
    id: "education",
    title: "Education",
    items: [
      {
        id: "education-1",
        title: "Brown University",
        description: "Bachelor's degree in Economics and Political Science",
        image: "/placeholder.svg?key=ebhz7",
        tags: ["Economics", "Political Science", "Ivy League"],
        era: "2004-2007",
        date: "2004-2008",
        category: "education",
        location: "providence",
      },
      {
        id: "education-2",
        title: "Yale School of Management",
        description: "Master of Business Administration (MBA)",
        image: "/yale-som-courtyard.png",
        tags: ["MBA", "Business", "Leadership"],
        era: "2016-2019",
        date: "2015-2017",
        category: "education",
        location: "new-haven",
      },
    ],
  },
  {
    id: "professional",
    title: "Professional Experience",
    items: [
      {
        id: "professional-1",
        title: "Management Consultant",
        description: "Strategic consulting for Fortune 500 companies",
        image: "/strategic-growth-presentation.png",
        tags: ["Strategy", "Analysis", "Leadership"],
        era: "2008-2011",
        date: "2008-2012",
        category: "professional",
        location: "nyc-det-cle",
      },
      {
        id: "professional-2",
        title: "Media & Entertainment Analytics",
        description: "Data-driven insights for media companies",
        image: "/media-analytics-dashboard-enhanced.png",
        tags: ["Analytics", "Media", "Entertainment"],
        era: "2023-2025",
        date: "2021-present",
        category: "professional",
        location: "nyc",
      },
      {
        id: "professional-3",
        title: "Sports Analytics Director",
        description: "Performance analytics for professional sports teams",
        image: "/dynamic-sports-analytics.png",
        tags: ["Sports", "Analytics", "Performance"],
        era: "2016-2019",
        date: "2018-2021",
        category: "professional",
        location: "miami-2",
      },
    ],
  },
  {
    id: "entrepreneurship",
    title: "Entrepreneurship",
    items: [
      {
        id: "entrepreneurship-1",
        title: "Tech Startup Founder",
        description: "Founded a data analytics platform for small businesses",
        image: "/vibrant-startup-hub.png",
        tags: ["Startup", "Technology", "Leadership"],
        era: "2012-2015",
        date: "2012-2015",
        category: "entrepreneurship",
        location: "miami-1",
      },
      {
        id: "entrepreneurship-2",
        title: "Angel Investor",
        description: "Early-stage investments in technology startups",
        image: "/placeholder.svg?height=480&width=640&query=venture capital meeting",
        tags: ["Investing", "Startups", "Mentorship"],
        era: "2020-2022",
        date: "2018-present",
        category: "entrepreneurship",
        location: "miami-2",
      },
    ],
  },
  {
    id: "projects",
    title: "Projects",
    items: [
      {
        id: "project-1",
        title: "AI-Powered Analytics Dashboard",
        description: "Developed an AI-powered analytics dashboard for media companies",
        image: "/placeholder.svg?height=480&width=640&query=AI analytics dashboard",
        tags: ["AI", "Analytics", "Dashboard"],
        era: "2023-2025",
        date: "2022-2023",
        category: "projects",
        location: "nyc",
      },
      {
        id: "project-2",
        title: "Sports Performance Prediction Model",
        description: "Created a machine learning model to predict athlete performance",
        image: "/placeholder.svg?height=480&width=640&query=sports performance data visualization",
        tags: ["Machine Learning", "Sports", "Prediction"],
        era: "2016-2019",
        date: "2019-2020",
        category: "projects",
        location: "miami-2",
      },
      {
        id: "project-3",
        title: "Economic Impact Study",
        description: "Conducted research on economic impact of policy changes",
        image: "/placeholder.svg?height=480&width=640&query=economic research graphs",
        tags: ["Economics", "Research", "Policy"],
        era: "2008-2011",
        date: "2010-2011",
        category: "projects",
        location: "nyc-det-cle",
      },
    ],
  },
]
