import { notFound } from "next/navigation"
import Image from "next/image"
import { Badge } from "@/components/ui/badge"
import { ExternalLink } from "lucide-react"
import { getContentById, getAllContent } from "@/lib/airtable"
import { getEraStyles } from "@/lib/era-styles"
import HeaderMenu from "@/components/header-menu"
import { getSkillsForDisplay } from "@/lib/skills-helper"
import SkillsByCategory from "@/components/skills-by-category"
import ToolIcon from "@/components/tool-icon"
import { getToolDisplayName } from "@/lib/tool-mappings"

export const dynamicParams = true // Allow dynamic params that aren't generated by generateStaticParams
export const revalidate = 0 // Disable caching for this page

export default async function ExperiencePage({ params }: { params: { slug: string } }) {
  // Find the experience item by slug
  const experience = await getContentById(params.slug)

  // Fetch all content to get the list of projects for the HeaderMenu
  const { items: allProjects } = await getAllContent()

  if (!experience) {
    notFound()
  }

  // FORCE SPECIFIC ERAS FOR KNOWN PAGES
  // This is a more aggressive approach to ensure the correct era is applied
  let forcedEra: string | undefined = undefined

  // Force Brown University to 2004-2007 era
  if (
    params.slug === "brown-university" ||
    experience.title.toLowerCase().includes("brown") ||
    (experience.company && experience.company.toLowerCase().includes("brown"))
  ) {
    forcedEra = "2004-2007"
  }

  // Force Yale to 2016-2019 era
  if (
    params.slug === "yale-school-of-management" ||
    experience.title.toLowerCase().includes("yale") ||
    (experience.company && experience.company.toLowerCase().includes("yale"))
  ) {
    forcedEra = "2016-2019"
  }

  // Ensure era is correctly set based on start year if not forced
  let correctedEra = forcedEra || experience.era

  if (!forcedEra) {
    // Map start year to correct era if not already forced
    const startYear = Number.parseInt(experience.startYear || "0", 10)
    if (startYear >= 2004 && startYear <= 2007) {
      correctedEra = "2004-2007"
    } else if (startYear >= 2008 && startYear <= 2011) {
      correctedEra = "2008-2011"
    } else if (startYear >= 2012 && startYear <= 2015) {
      correctedEra = "2012-2015"
    } else if (startYear >= 2016 && startYear <= 2019) {
      correctedEra = "2016-2019"
    } else if (startYear >= 2020 && startYear <= 2022) {
      correctedEra = "2020-2022"
    } else if (startYear >= 2023) {
      correctedEra = "2023-2025"
    }
  }

  // Use the corrected era for styling
  const eraStyles = getEraStyles(correctedEra)

  // Update the era in the experience object
  experience.era = correctedEra

  // Get the human-readable skills using our helper function
  const displaySkills = getSkillsForDisplay(experience)

  // Create era-specific class name for the page
  const eraClassName = `era-${experience.era.replace(/\s+/g, "-").toLowerCase()}`

  // Force a unique timestamp to prevent caching
  const timestamp = Date.now()

  // Define era-specific styles directly in the component
  // This ensures they're applied regardless of CSS caching
  const getEraBackgroundColor = (era: string) => {
    switch (era) {
      case "2004-2007":
        return "black"
      case "2008-2011":
        return "#111827"
      case "2012-2015":
        return "#fffbeb"
      case "2016-2019":
        return "#581c87"
      case "2020-2022":
        return "#f9fafb"
      default:
        return "white"
    }
  }

  const getEraTextColor = (era: string) => {
    switch (era) {
      case "2004-2007":
        return "white"
      case "2008-2011":
        return "#e5e7eb"
      case "2012-2015":
        return "#1f2937"
      case "2016-2019":
        return "#fbcfe8"
      case "2020-2022":
        return "#4b5563"
      default:
        return "#1f2937"
    }
  }

  const getEraAccentColor = (era: string) => {
    switch (era) {
      case "2004-2007":
        return "#ca8a04"
      case "2008-2011":
        return "#6b7280"
      case "2012-2015":
        return "#92400e"
      case "2016-2019":
        return "#9333ea"
      case "2020-2022":
        return "#4b5563"
      default:
        return "#2563eb"
    }
  }

  const getEraFontFamily = (era: string) => {
    switch (era) {
      case "2004-2007":
        return "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif"
      case "2008-2011":
        return "Georgia, 'Times New Roman', Times, serif"
      case "2012-2015":
        return "'Times New Roman', Times, serif"
      case "2016-2019":
        return "'Courier New', Courier, monospace"
      case "2020-2022":
        return "Helvetica, Arial, sans-serif"
      default:
        return "Inter, system-ui, -apple-system, sans-serif"
    }
  }

  // Get the background and text colors based on the era
  const bgColor = getEraBackgroundColor(experience.era)
  const textColor = getEraTextColor(experience.era)
  const accentColor = getEraAccentColor(experience.era)
  const fontFamily = getEraFontFamily(experience.era)

  return (
    <>
      {/* Pass the allProjects to the HeaderMenu component */}
      <HeaderMenu projects={allProjects} />

      <div
        className={`min-h-screen ${eraClassName}`}
        style={{
          backgroundColor: bgColor,
          color: textColor,
        }}
        data-era={experience.era}
      >
        {/* Hero Section */}
        <div className="relative border-b overflow-hidden">
          {/* Hero Image Container */}
          <div className="relative aspect-[21/9] md:aspect-[3/1] w-full">
            <Image
              src={
                experience.image ||
                `/placeholder.svg?height=1080&width=1920&query=${encodeURIComponent(experience.title) || "/placeholder.svg"}`
              }
              alt={experience.title}
              fill
              className={`object-cover ${eraStyles.filter}`}
              priority
              quality={100}
              sizes="100vw"
              unoptimized={experience.image?.includes("cloudinary.com")}
            />
          </div>

          {/* Gradient overlay */}
          <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent" />

          {/* Content */}
          <div className="absolute bottom-0 left-0 w-full p-6 md:p-12 z-10">
            <div className="max-w-4xl">
              <div className="mb-2 flex items-center">
                <Badge variant="outline" className={`text-xs ${eraStyles.badge} mr-2 bg-white/90`}>
                  {experience.type.toUpperCase()}
                </Badge>
                <span className={`text-sm text-white/90`}>{experience.startYear}</span>
              </div>

              <h1 className={`text-3xl md:text-5xl font-bold mb-4 text-white drop-shadow-md`}>{experience.title}</h1>

              {experience.company && (
                <div className="flex items-center space-x-4 mb-6">
                  {experience.logo && (
                    <div className="h-8 w-8 relative mr-2 bg-white/90 rounded-full p-1">
                      <Image
                        src={experience.logo || "/placeholder.svg"}
                        alt={experience.company}
                        fill
                        className="object-contain"
                      />
                    </div>
                  )}
                  <span className="text-lg font-medium text-white drop-shadow-md">{experience.company}</span>
                </div>
              )}

              <p className={`text-lg max-w-3xl text-white/90 drop-shadow-md`}>{experience.description}</p>
            </div>
          </div>
        </div>

        {/* Navigation Tabs */}
        <div
          className="border-b sticky top-16 z-20 shadow-sm"
          style={{
            backgroundColor:
              experience.era === "2004-2007"
                ? "#111111"
                : experience.era === "2008-2011"
                  ? "#1f2937"
                  : experience.era === "2012-2015"
                    ? "#fef3c7"
                    : experience.era === "2016-2019"
                      ? "#6b21a8"
                      : experience.era === "2020-2022"
                        ? "white"
                        : "#f8fafc",
            borderColor: accentColor,
          }}
        >
          <div className="flex px-6 md:px-12">
            <div
              className="py-4 px-2 border-b-2 font-medium"
              style={{
                borderColor: accentColor,
                color:
                  experience.era === "2004-2007"
                    ? "#ca8a04"
                    : experience.era === "2008-2011"
                      ? "white"
                      : experience.era === "2012-2015"
                        ? "#92400e"
                        : experience.era === "2016-2019"
                          ? "#fbcfe8"
                          : experience.era === "2020-2022"
                            ? "#4b5563"
                            : "#2563eb",
              }}
            >
              Overview
            </div>
            <div className="py-4 px-2 text-gray-400">Details</div>
            <div className="py-4 px-2 text-gray-400">Gallery</div>
            <div className="py-4 px-2 text-gray-400">Related</div>
          </div>
        </div>

        {/* Overview Section */}
        <section className="py-12 px-6 md:px-12">
          <div className="max-w-4xl mx-auto">
            <h2
              className="text-2xl font-bold mb-6"
              style={{
                color: accentColor,
                fontFamily: fontFamily,
                fontStyle: experience.era === "2012-2015" ? "italic" : "normal",
                textTransform: experience.era === "2004-2007" || experience.era === "2016-2019" ? "uppercase" : "none",
                letterSpacing: experience.era === "2016-2019" ? "0.1em" : "normal",
              }}
            >
              Overview
            </h2>

            <div
              className="prose max-w-none mb-12"
              style={{
                color:
                  experience.era === "2004-2007"
                    ? "#d1d5db"
                    : experience.era === "2008-2011"
                      ? "#d1d5db"
                      : experience.era === "2012-2015"
                        ? "#4b5563"
                        : experience.era === "2016-2019"
                          ? "#e9d5ff"
                          : experience.era === "2020-2022"
                            ? "#4b5563"
                            : "#4b5563",
                fontFamily:
                  experience.era === "2016-2019"
                    ? "monospace"
                    : experience.era === "2012-2015"
                      ? "serif"
                      : "sans-serif",
              }}
            >
              {experience.content ? (
                <div dangerouslySetInnerHTML={{ __html: experience.content }} />
              ) : (
                <p>
                  This is an extended description of the {experience.title} experience at {experience.company}.
                </p>
              )}
            </div>

            {/* Skills Section */}
            {displaySkills.length > 0 && (
              <div className="mb-12">
                <h3
                  className="text-xl font-semibold mb-4"
                  style={{
                    color: accentColor,
                    fontFamily: fontFamily,
                  }}
                >
                  Skills
                </h3>
                <SkillsByCategory item={experience} badgeClassName={eraStyles.badge} />
              </div>
            )}

            {/* Tools Section */}
            {Array.isArray(experience.tools) && experience.tools.length > 0 && (
              <div className="mb-12">
                <h3
                  className="text-xl font-semibold mb-4"
                  style={{
                    color: accentColor,
                    fontFamily: fontFamily,
                  }}
                >
                  Tools
                </h3>
                <div className="flex flex-wrap gap-6">
                  {experience.tools.map((tool, index) => (
                    <div key={index} className="flex flex-col items-center">
                      <div
                        className="w-16 h-16 rounded-lg flex items-center justify-center mb-2 p-2 relative"
                        style={{
                          backgroundColor:
                            experience.era === "2004-2007"
                              ? "#1f2937"
                              : experience.era === "2008-2011"
                                ? "#1f2937"
                                : experience.era === "2012-2015"
                                  ? "white"
                                  : experience.era === "2016-2019"
                                    ? "#4c1d95"
                                    : experience.era === "2020-2022"
                                      ? "white"
                                      : "white",
                          borderWidth: "2px",
                          borderColor: accentColor,
                          boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
                        }}
                      >
                        <ToolIcon
                          name={tool.name}
                          originalId={tool.originalId}
                          logo={
                            tool.logo ? `${tool.logo}${tool.logo.includes("?") ? "&" : "?"}t=${timestamp}` : undefined
                          }
                        />
                      </div>
                      <span className="text-sm text-center font-medium">{getToolDisplayName(tool)}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* External Link */}
            {experience.link && (
              <div className="mb-12">
                <a
                  href={experience.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center px-4 py-2 rounded"
                  style={{
                    backgroundColor:
                      experience.era === "2004-2007"
                        ? "#ca8a04"
                        : experience.era === "2008-2011"
                          ? "#6b7280"
                          : experience.era === "2012-2015"
                            ? "#92400e"
                            : experience.era === "2016-2019"
                              ? "#9333ea"
                              : experience.era === "2020-2022"
                                ? "white"
                                : "white",
                    color:
                      experience.era === "2004-2007"
                        ? "black"
                        : experience.era === "2008-2011"
                          ? "white"
                          : experience.era === "2012-2015"
                            ? "white"
                            : experience.era === "2016-2019"
                              ? "white"
                              : experience.era === "2020-2022"
                                ? "#4b5563"
                                : "#2563eb",
                    borderWidth: experience.era === "2020-2022" || experience.era === "2023-2025" ? "1px" : "0",
                    borderColor: experience.era === "2020-2022" ? "#4b5563" : "#2563eb",
                    borderRadius:
                      experience.era === "2016-2019" || experience.era === "2020-2022" ? "9999px" : "0.25rem",
                    fontWeight: "600",
                    textTransform:
                      experience.era === "2004-2007" || experience.era === "2012-2015" ? "uppercase" : "normal",
                    boxShadow:
                      experience.era === "2004-2007" || experience.era === "2016-2019"
                        ? "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)"
                        : "none",
                  }}
                >
                  <ExternalLink className="h-4 w-4 mr-2" />
                  View Project
                </a>
              </div>
            )}
          </div>
        </section>

        {/* Project Images Section */}
        {experience.projectImages && experience.projectImages.length > 0 && (
          <section
            className="py-12 px-6 md:px-12 border-t"
            style={{
              borderColor: accentColor,
            }}
          >
            <div className="max-w-4xl mx-auto">
              <h2
                className="text-2xl font-bold mb-6"
                style={{
                  color: accentColor,
                  fontFamily: fontFamily,
                  fontStyle: experience.era === "2012-2015" ? "italic" : "normal",
                  textTransform:
                    experience.era === "2004-2007" || experience.era === "2016-2019" ? "uppercase" : "none",
                }}
              >
                Gallery
              </h2>

              <div className="space-y-12">
                {experience.projectImages.map((image, index) => (
                  <div key={index} className="space-y-2">
                    <div
                      className="relative aspect-video w-full overflow-hidden rounded-lg shadow-md"
                      style={{
                        borderLeftWidth: "4px",
                        borderColor: accentColor,
                      }}
                    >
                      <Image
                        src={image.url || "/placeholder.svg"}
                        alt={image.caption || `Project image ${index + 1}`}
                        fill
                        className={`object-cover ${eraStyles.filter}`}
                        quality={100}
                        sizes="(max-width: 768px) 100vw, 800px"
                        unoptimized={image.url?.includes("cloudinary.com")}
                      />
                    </div>
                    {image.caption && <p className="text-sm italic text-center">{image.caption}</p>}
                  </div>
                ))}
              </div>
            </div>
          </section>
        )}
      </div>
    </>
  )
}
